<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('indexheaderdologin') ?>
<?php $users = Data::get('users') ?>

  <!-- container -->
  <div class="container">

    <ol class="breadcrumb">
      <li><a href="<?=URL::toRoute('perfil/index')?>">Principal</a></li>
      <li class="active">Perfil</li>
    </ol>

    <h2 class="text-left top-space">O meu Perfil</h2>
    <h2 class="top-space"></h2>
    <div class="row">
      <div class="col-sm-12">
        <table class="table table-striped"><thead><th><h3>Nome de utilizador</h3></th><th><h3>Nome</h3></th><th><h3>Morada</h3></th><th><h3>Email</h3></th><th><h3>Nif</h3></th><th><h3>Contato</h3></th><th><h3>Role</h3></th></thead>
          <tbody>
          <?php foreach ($users as $user) { ?>
            <tr>
              <td><?=$user->username?></td>
              <td><?=$user->name?></td>
              <td><?=$user->morada?></td>
              <td><?=$user->email?></td>
              <td><?=$user->nif?></td>
              <td><?=$user->telefone?></td>
              <td><?=$user->role?></td>
              <td>
                <a href="<?=Url::toRoute('perfil/edit', $user->id)?>" class="btn btn-info" role="button">Atualizar dados</a>
              </td>
            </tr>
          <?php } ?>

          </tbody>

        </table>

      </div>
    </div> <!-- /row -->

  </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
