<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminappheader') ?>
<?php $plane = Data::get('plane') ?>
<?php ErrMgr::attach($plane) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Editar Avião</h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">

                    <hr>

                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('plane/update', $plane->id)?>">

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="reference">Referencia: <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input required type="text" value="<?=$plane->reference?>" class="form-control" required name="reference" placeholder="Insira a referência">
                                <?= ErrMgr::bind('reference') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="capacity">Capacidade: <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input required type="number" value="<?=$plane->capacity?>" class="form-control" required name="capacity" placeholder="Insira a capacidade">
                                <?= ErrMgr::bind('capacity') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="type">Tipo: <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input required type="text" value="<?=$plane->type?>"  class="form-control" required name="type" placeholder="Insira o tipo de avião">
                                <?= ErrMgr::bind('type') ?>
                            </div>
                        </div>

                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>
                </div>
                </form>
            </div>
    </div>



    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

