<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorappheader') ?>
<?php $flight = Data::get('flight')?>
<?php $airports= Data::get('airports')?>
<?php ErrMgr::attach($flight) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Novo Voo</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('flight/store')?>">
                            <div class="top-margin">
                                <label>Data de Origem <span class="text-danger">*</span></label>
                                <input required type="text" value="<?=$flight->dtorigin?>" name="dtorigin" class="form-control" placeholder="Insira aaaa/mm/dd">
                                <?= ErrMgr::bind('dtdestino') ?>
                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Data de Destino <span class="text-danger">*</span></label>
                                <input required type="text" value="<?=$flight->dtdestination?>" name="dtdestination" class="form-control" placeholder="Insira aaaa/mm/dd">
                                <?= ErrMgr::bind('dtdestination') ?>
                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Hora de Partida <span class="text-danger">*</span></label>
                                <input required type="text" value="<?=$flight->hrorigin?>" name="hrorigin" class="form-control" placeholder="Insira HH:mm:ss">
                                <?= ErrMgr::bind('hrorigin') ?>
                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Hora de Chegada <span class="text-danger">*</span></label>
                                <input required type="text" value="<?=$flight->hrdestination?>" name="hrdestination" class="form-control" placeholder="Insira HH:mm:ss">
                                <?= ErrMgr::bind('hrdestination') ?>
                            </div>
                          <div class="top-margin">
                            <label>Local de origem <span class="text-danger">*</span></label>
                            <input required type="text" value="<?=$flight->origem?>" name="origem" class="form-control" placeholder="Insira o local de origem">
                            <?= ErrMgr::bind('origem') ?>
                          </div>
                          <div class="top-margin">
                            <label>Local de destino <span class="text-danger">*</span></label>
                            <input required type="text" value="<?=$flight->destino?>" name="destino" class="form-control" placeholder="Insira o local de destino">
                            <?= ErrMgr::bind('destino') ?>
                          </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Novo</button>
                            </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
