<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorappheader') ?>
<?php $flight = Data::get('flight') ?>
<?php ErrMgr::attach($flight) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Editar Aeroporto</h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">

                    <hr>

                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('flight/update', $flight->id)?>">

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="name">Data de partida: <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input required type="text" value="<?=$flight->dtorigin?>" class="form-control" required name="dtorigin" placeholder="Insira aaaa/mm/dd">
                                <?= ErrMgr::bind('dtorigin') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="localization">Data de chegada: <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input required type="text" value="<?=$flight->dtdestination?>" class="form-control" required name="dtdestination" placeholder="Insira aaaa/mm/dd">
                                <?= ErrMgr::bind('dtdestination') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="contact">Hora de partida: <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input required type="text" value="<?=$flight->hrorigin?>"  class="form-control" required name="hrorigin" placeholder="Insira HH:mm:ss">
                                <?= ErrMgr::bind('contact') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="country">Hora de chegada: <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input required type="text" value="<?=$flight->hrdestination?>" class="form-control" required name="hrdestination" placeholder="Insira HH:mm:ss">
                                <?= ErrMgr::bind('hrdestination') ?>
                            </div>
                        </div>

                      <div class="form-group">
                        <label class="control-label col-sm-2" for="country">Local de origem: <span class="text-danger">*</span></label>
                        <div class="col-sm-6">
                          <input required type="text" value="<?=$flight->origem?>" class="form-control" required name="origem" placeholder="Insira HH:mm:ss">
                          <?= ErrMgr::bind('origem') ?>
                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-sm-2" for="country">Local de destino: <span class="text-danger">*</span></label>
                        <div class="col-sm-6">
                          <input required type="text" value="<?=$flight->destino?>" class="form-control" required name="destino" placeholder="Insira HH:mm:ss">
                          <?= ErrMgr::bind('destino') ?>
                        </div>
                      </div>

                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>
                </div>
                </form>
            </div>
    </div>



    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('userappfooter') ?>
