<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorappheader') ?>
<?php $flights = Data::get('flights') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="<?=URL::toRoute('gestorvoo/index')?>">Principal</a></li>
            <li class="active">Voos</li>
        </ol>

        <h2 class="text-left top-space">Voos</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>ID</h3></th><th><h3>Preço</h3></th><th><h3>ID Aeroporto Origem</h3></th><th><h3>Data Origem</h3></th><th><h3>Hora Partida</h3></th><th><h3>ID Aeroporto Destino</h3></th><th><h3>Data Destino</h3></th><th><h3>Hora Chegada</h3></th></thead>
                    <tbody>
                    <?php foreach ($flights as $flight) { ?>
                        <tr>
                            <td class="text-center"><?=$flight->id?></td>
                            <td class="text-center"><?=$flight->precoidaevolta?></td>
                            <td class="text-center"><?=$flight->idairportorigin?></td>
                            <td class="text-center"><?=$flight->dtorigin?></td>
                            <td class="text-center"><?=$flight->hrorigin?></td>
                            <td class="text-center"><?=$flight->idairportdestination?></td>
                            <td class="text-center"><?=$flight->dtdestination?></td>
                            <td class="text-center"><?=$flight->hrdestination?></td>
                            <td>
                                <a href="<?=Url::toRoute('flight/edit', $flight->id)?>" class="btn btn-info" role="button">Editar</a>
                                <a href="<?=Url::toRoute('layover/index', $flight->id)?>" class="btn btn-warning" role="button">Escalas</a>
                                <a href="<?=Url::toRoute('flight/destroy', $flight->id)?>" class="btn btn-danger" role="button">Apagar</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <h3>Adicionar um novo Voo</h3>
                <p>
                    <a href="<?=Url::toRoute('flight/create')?>" class="btn btn-info" role="button">Novo</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
