<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

// Incluir o layout do header
Layout::includeLayout('operadorheader') ?>

<?php $user = Data::get('user') ?>
<?php ErrMgr::attach($user) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Realizar check-in de passageiro</h1>
            </header>

    </article>
    <!-- /Article -->

</div>
</div>
<!-- /container -->

<!-- Incluir o layout do footer -->
<?php Layout::includeLayout('footer') ?>
