<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">

                <div class="col-md-3 widget">
                    <h3 class="widget-title">Contact</h3>
                    <div class="widget-body">
                        <p>+351 244 300 800<br>
                            <br>
                            School of Technology and Management (ESTG)<br>
                            Polytechnic Institute of Leiria<br>
                            Morro do Lena, Campus 2<br>
                            2400 Leiria<br>
                            Portugal<br>
                        </p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

    <div class="footer2">
        <div class="container">
            <div class="row">

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="text-right">
                            Copyright &copy; 2016-2021, Silvio Priem Mendes, PhD. <br> Site template by Sergey Pozhilov.
                        </p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?= AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>
