<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorappheader') ?>
<?php $flight = Data::get('flight') ?>
<?php ErrMgr::attach($flight) ?>

<!-- container -->
<div class="container">

  <div class="row">

    <!-- Article main content -->
    <article class="col-xs-12 maincontent">
      <header class="page-header">
        <h1 class="page-title">Editar voos</h1>
      </header>

      <div class="panel panel-default">
        <div class="panel-body">

          <hr>

          <form class="form-horizontal" method="post" action="<?=Url::toRoute('flight/update', $flight->id)?>">

            <div class="form-group">
              <label class="control-label col-sm-2" for="name">Nome:<span class="text-danger">*</span></label>
              <div class="col-sm-6">
                <input required type="text" value="<?=$flight->name?>" class="form-control" required name="name" placeholder="Insira o nome">
                <?= ErrMgr::bind('name') ?>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-2" for="name">Origem:<span class="text-danger">*</span></label>
              <div class="col-sm-6">
                <input required type="text" value="<?=$flight->origem?>" class="form-control" required name="origem" placeholder="Insira a origem">
                <?= ErrMgr::bind('origem') ?>
              </div>
            </div>

              <div class="form-group">
                <label class="control-label col-sm-2" for="name">Destino:<span class="text-danger">*</span></label>
                <div class="col-sm-6">
                  <input required type="text" value="<?=$flight->destino?>" class="form-control" required name="destino" placeholder="Insira o destino">
                  <?= ErrMgr::bind('destino') ?>
                </div>
              </div>

                <div class="form-group">
                  <label class="control-label col-sm-2" for="name">Data de partida:<span class="text-danger">*</span></label>
                  <div class="col-sm-6">
                    <input required type="text" value="<?=$flight->datapartida?>" class="form-control" required name="datapartida" placeholder="Insira a data de partida">
                    <?= ErrMgr::bind('datapartida') ?>
                  </div>
                </div>

                  <div class="form-group">
                    <label class="control-label col-sm-2" for="name">Data de regresso:<span class="text-danger">*</span></label>
                    <div class="col-sm-6">
                      <input required type="text" value="<?=$flight->dataregresso?>" class="form-control" required name="dataregresso" placeholder="Insira a data de regresso">
                      <?= ErrMgr::bind('dataregresso') ?>
                    </div>
                  </div>

                    <div class="form-group">
                      <label class="control-label col-sm-2" for="name">Preço:<span class="text-danger">*</span></label>
                      <div class="col-sm-6">
                        <input required type="text" value="<?=$flight->preco?>" class="form-control" required name="preco" placeholder="Insira o preço">
                        <?= ErrMgr::bind('preco') ?>
                      </div>
                    </div>

              <hr>

              <div class="col-lg-4 text-right">
                <button class="btn btn-default" type="submit">Guardar</button>
              </div>
            </div>
          </form>
        </div>
      </div>

    </article>
    <!-- /Article -->

  </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
