<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminappheader') ?>
<?php $users = Data::get('users') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=URL::toRoute('admin/index')?>">Principal</a></li>
        <li class="active">Membros do Staff</li>
    </ol>

    <h2 class="text-left top-space">Membros do Staff</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped"><thead><th><h3>Username</h3></th><th><h3>Nome</h3></th><th><h3>Morada</h3></th><th><h3>Email</h3></th><th><h3>Nif</h3></th><th><h3>Contacto</h3></th><th><h3>Role</h3></th></thead>
                <tbody>
                <?php foreach ($users as $user) { ?>
                    <tr>
                        <td><?=$user->username?></td>
                        <td><?=$user->name?></td>
                        <td><?=$user->morada?></td>
                        <td><?=$user->email?></td>
                        <td><?=$user->nif?></td>
                        <td><?=$user->telefone?></td>
                        <td><?=$user->role?></td>
                        <td>
                            <a href="<?=Url::toRoute('user/edit', $user->id)?>" class="btn btn-info" role="button">Editar</a>
                            <a href="<?=Url::toRoute('user/destroy', $user->id)?>" class="btn btn-warning" role="button">Apagar</a>
                        </td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <h3>Criar um novo Membro do Staff</h3>
            <p>
                <a href="<?=Url::toRoute('user/create')?>" class="btn btn-info" role="button">Adicionar</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('userappfooter')?>
