<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Login</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="thin text-center">Entre com a sua conta</h3>
                        <p class="text-center text-muted" > <a href="<?=URL::toRoute('login/registerform')?>">Registe-se</a> caso não tenha conta criada</p>
                        <hr>

                        <form method="post" action="<?=URL::toRoute('login/dologin')?>">
                            <div class="top-margin">
                                <label>Nome de utilizador <span class="text-danger">*</span></label>
                                <input type="text" name="username" class="form-control" placeholder="Insira o seu nome de utilizador">
                            </div>
                            <div class="top-margin">
                                <label>Palavra-passe <span class="text-danger">*</span></label>
                                <input type="password" name="password" class="form-control" placeholder="Insira a sua palavra-passe">
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-lg-8">
                                    <b><a href=""></a></b>
                                </div>
                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Entrar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('userappfooter') ?>
