<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('indexheader') ?>

<?php $user = Data::get('user')?>
<?php ErrMgr::attach($user) ?>
    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Registo</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Cria a tua conta</h3>
                            <hr>
                            <form method="post" action="<?=URL::toRoute('login/doregistration')?>">
                                <div class="top-margin">
                                    <label>Nome <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->name?>" name="name" class="form-control" placeholder="Insira o seu nome">
                                    <?= ErrMgr::bind('name') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Morada <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->morada?>" name="morada" class="form-control" placeholder="Insira a sua morada">
                                    <?= ErrMgr::bind('morada') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->email?>" name="email" class="form-control" placeholder="Insira o seu email">
                                    <?= ErrMgr::bind('email') ?>
                                </div>
                                <div class="top-margin">
                                    <label>NIF <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->nif?>" name="nif" class="form-control" placeholder="Insira o seu nif">
                                    <?= ErrMgr::bind('nif') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Contacto <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->telefone?>" name="telefone" class="form-control" placeholder="Insira o seu telefone">
                                    <?= ErrMgr::bind('telefone') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Nome de utilizador <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->username?>" name="username" class="form-control" placeholder="Insira o seu nome de utilizador">
                                    <?= ErrMgr::bind('username') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Palavra passe <span class="text-danger">*</span></label>
                                    <input type="password" value="<?=$user->password?>" name="password" class="form-control" placeholder="Insira a sua palavra-passe">
                                    <?= ErrMgr::bind('password') ?>
                                </div>
                                <hr>
                                    <div class="col-lg-4 text-right">
                                        <button class="btn btn-action" type="submit">Criar conta</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('userappfooter') ?>
