<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('gestorappheader') ?>
<?php $planelayover = Data::get('legplane')?>
<?php $planes = Data::get('planes')?>
<?php $idleg = Data::get('idleg')?>
<?php ErrMgr::attach($planelayover) ?>


    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Adicionar Avião à Escala</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>
                            <form method="post" action="<?=Url::toRoute('planelayover/store')?>">
                                <div>
                                    <input type="hidden" value="<?=$idleg?>" name="idleg">
                                </div>
                                <div>
                                    <label>Aeroporto de Origem<span class="text-danger">*</span></label>
                                    <select name="idplane">
                                        <?php
                                        foreach ($planes as $plane){
                                            echo '<option value="' . $plane->id . '">' .$plane->reference.'</option>';
                                        }
                                        ?>
                                    </select>
                                </div>
                                <hr>
                                <div class="top-margin">
                                    <label>Numero de Checkins <span class="text-danger">*</span></label>
                                    <input required type="text" value="<?=$planelayover->checkinnum?>" name="checkinnum" class="form-control" placeholder="Insira o numero de checkins">
                                    <?= ErrMgr::bind('checkinnum') ?>
                                </div>
                                <hr>
                                <div class="top-margin">
                                    <label>Numero de Bilhetes Vendidos <span class="text-danger">*</span></label>
                                    <input required type="text" value="<?=$planelayover->ticketssold?>" name="ticketssold" class="form-control" placeholder="Insira o numero de bilhetes vendidos">
                                    <?= ErrMgr::bind('ticketssold') ?>
                                </div>

                                <hr>

                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Novo</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('userappfooter') ?>
