<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorappheader') ?>
<?php $flight = Data::get('$flight')?>
<?php ErrMgr::attach($flight) ?>


<!-- container -->
<div class="container">

  <div class="row">

    <!-- Article main content -->
    <article class="col-xs-12 maincontent">
      <header class="page-header">
        <h1 class="page-title">Adicionar Novo Voo</h1>
      </header>

      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <hr>
            <form method="post" action="<?=Url::toRoute('flight/store')?>">

              <div class="top-margin">
                <label>Nome <span class="text-danger">*</span></label>
                <input required type="text" value="<?=$flight->name?>" name="name" class="form-control" placeholder="Insira o nome">
                <?= ErrMgr::bind('name') ?>
              </div>

              <div class="top-margin">
                <label>Origem <span class="text-danger">*</span></label>
                <input required type="text" value="<?=$flight->origem?>" name="origem" class="form-control" placeholder="Insira a origem">
                <?= ErrMgr::bind('origem') ?>
              </div>

              <div class="top-margin">
                <label>Destino <span class="text-danger">*</span></label>
                <input required type="text" value="<?=$flight->destino?>" name="destino" class="form-control" placeholder="Insira o destino">
                <?= ErrMgr::bind('destino') ?>
              </div>

              <div class="top-margin">
                <label>Data de partida <span class="text-danger">*</span></label>
                <input required type="text" value="<?=$flight->datapartida?>" name="dataPartida" class="form-control" placeholder="Insira a data de partida">
                <?= ErrMgr::bind('dataPartida') ?>
              </div>

              <div class="top-margin">
                <label>Data de regresso <span class="text-danger">*</span></label>
                <input required type="text" value="<?=$flight->dataregresso?>" name="dataRegresso" class="form-control" placeholder="Insira a data de regresso">
                <?= ErrMgr::bind('dataRegresso') ?>
              </div>

              <div class="top-margin">
                <label>Preco <span class="text-danger">*</span></label>
                <input required type="text" value="<?=$flight->preco?>" name="preco" class="form-control" placeholder="Insira o preço">
                <?= ErrMgr::bind('preco') ?>
              </div>

              <hr>

              <div class="col-lg-4 text-right">
                <button class="btn btn-action" type="submit">Adicionar</button>
              </div>

          </div>
          </form>
        </div>
      </div>

  </div>

  </article>
  <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
