<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('operadorheader') ?>
<?php $flight = Data::get('flight') ?>
<?php ErrMgr::attach($flight) ?>

<!-- container -->
<div class="container">

  <div class="row">

    <!-- Article main content -->
    <article class="col-xs-12 maincontent">
      <header class="page-header">
        <h1 class="page-title">Detalhes do voo selecionado</h1>
      </header>

      <div class="panel panel-default">
        <div class="panel-body">

          <hr>

          <form class="form-horizontal" method="post" action="<?=Url::toRoute('flight/update', $flight->id)?>">

            <div class="form-group">
              <label class="control-label col-sm-2" for="name">Id do voo:<span class="text-danger">*</span></label>
              <div class="col-sm-6">
                <input required type="text" value="<?=$flight->id?>" class="form-control" required name="id" placeholder="Id do voo" readonly>
                <?= ErrMgr::bind('id') ?>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-2" for="name">Preço:<span class="text-danger">*</span></label>
              <div class="col-sm-6">
                <input required type="text" value="<?=$flight->precoidaevolta?>" class="form-control" required name="precoidaevolta" placeholder="Insira o preço" readonly>
                <?= ErrMgr::bind('precoidaevolta') ?>
              </div>
            </div>

              <div class="form-group">
                <label class="control-label col-sm-2" for="name">Aeroporto de origem:<span class="text-danger">*</span></label>
                <div class="col-sm-6">
                  <input required type="text" value="<?=$flight->idairportorigin?>" class="form-control" required name="idairportorigin" placeholder="Insira o aeroporto de origem" readonly>
                  <?= ErrMgr::bind('idairportorigin') ?>
                </div>
              </div>

                <div class="form-group">
                  <label class="control-label col-sm-2" for="name">Data de partida:<span class="text-danger">*</span></label>
                  <div class="col-sm-6">
                    <input required type="text" value="<?=$flight->dtorigin?>" class="form-control" required name="dtorigin" placeholder="Insira a data de origem" readonly>
                    <?= ErrMgr::bind('dtorigin') ?>
                  </div>
                </div>

                  <div class="form-group">
                    <label class="control-label col-sm-2" for="name">Hora de partida:<span class="text-danger">*</span></label>
                    <div class="col-sm-6">
                      <input required type="text" value="<?=$flight->hrorigin?>" class="form-control" required name="hrorigin" placeholder="Insira a hora de origem" readonly>
                      <?= ErrMgr::bind('hrorigin') ?>
                    </div>
                  </div>

            <div class="form-group">
              <label class="control-label col-sm-2" for="name">Aeroporto de destino:<span class="text-danger">*</span></label>
              <div class="col-sm-6">
                <input required type="text" value="<?=$flight->idairportdestination?>" class="form-control" required name="idairportdestination" placeholder="Insira o aeroporto de destino" readonly>
                <?= ErrMgr::bind('idairportdestination') ?>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-2" for="name">Data de destino:<span class="text-danger">*</span></label>
              <div class="col-sm-6">
                <input required type="text" value="<?=$flight->dtdestination?>" class="form-control" required name="dtdestination" placeholder="Insira a data de destino" readonly>
                <?= ErrMgr::bind('dtdestination') ?>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-2" for="name">Hora de destino:<span class="text-danger">*</span></label>
              <div class="col-sm-6">
                <input required type="text" value="<?=$flight->hrdestination?>" class="form-control" required name="hrdestination" placeholder="Insira a hora de destino" readonly>
                <?= ErrMgr::bind('hrdestination') ?>
              </div>
            </div>

            <hr>

            </div>
          </form>
        </div>
      </div>



    </article>
    <!-- /Article -->

  </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
