<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('operadorheader') ?>
<?php $flights = Data::get('flights') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="<?=URL::toRoute('gestorvoo/index')?>">Principal</a></li>
            <li class="active">Voos</li>
        </ol>

        <h2 class="text-left top-space">Voos</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h4>Id</h4></th><th><h4>Preço</h4></th><th><h4>Aeroporto origem</h4></th><th><h4>Data de origem</h4></th><th><h4>Hora de origem</h4></th><th><h4>Aeroporto destino</h4></th><th><h4>Data de destino</h4><th><h4>Hora de destino</h4></th></th></thead>
                    <tbody>
                    <?php foreach ($flights as $flight) { ?>
                        <tr>
                          <td class="text-center"><?=$flight->id?></td>
                          <td class="text-center"><?=$flight->precoidaevolta?></td>
                          <td class="text-center"><?=$flight->idairportorigin?></td>
                          <td class="text-center"><?=$flight->dtorigin?></td>
                          <td class="text-center"><?=$flight->hrorigin?></td>
                          <td class="text-center"><?=$flight->idairportdestination?></td>
                          <td class="text-center"><?=$flight->dtdestination?></td>
                          <td class="text-center"><?=$flight->hrdestination?></td>
                          <td>
                                <a href="<?=Url::toRoute('detalhesvoo/edit', $flight->id)?>" class="btn btn-info" role="button">Detalhes</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
